### ISSUE TITLE
Elastic Beanstalk not working

### ISSUE THREAD

**Issue by arnfinn** [mong/qmongjs#256]
Docker container quit unexpectedly.

From `/aws/elasticbeanstalk/qa-mong-api/var/log/eb-engine.log`:

```
2021/02/22 15:24:20.019928 [INFO] Executing instruction: GetToggleForceRotate
--
2021/02/22 15:24:20.019947 [INFO] Checking if logs need forced rotation
2021/02/22 15:24:20.019967 [INFO] Running command /bin/sh -c /opt/aws/bin/cfn-get-metadata -s arn:aws:cloudformation:eu-west-1:247247832514:stack/awseb-e-izypzzp3ev-stack/ddc07f90-7035-11eb-a1ee-024c6ad462dd -r AWSEBAutoScalingGroup --region eu-west-1
2021/02/22 15:24:20.654976 [INFO] Running command /bin/sh -c /opt/aws/bin/cfn-get-metadata -s arn:aws:cloudformation:eu-west-1:247247832514:stack/awseb-e-izypzzp3ev-stack/ddc07f90-7035-11eb-a1ee-024c6ad462dd -r AWSEBBeanstalkMetadata --region eu-west-1
2021/02/22 15:24:21.013328 [INFO] Procfile not found. Generating default rsyslog config
2021/02/22 15:24:21.014632 [INFO] Running command /bin/sh -c systemctl restart rsyslog.service
2021/02/22 15:24:21.047336 [INFO] Executing instruction: Configure Docker Logging
2021/02/22 15:24:21.063419 [INFO] Executing instruction: PostBuildEbExtension
2021/02/22 15:24:21.063439 [INFO] Starting executing the config set Infra-EmbeddedPostBuild.
2021/02/22 15:24:21.063457 [INFO] Running command /bin/sh -c /opt/aws/bin/cfn-init -s arn:aws:cloudformation:eu-west-1:247247832514:stack/awseb-e-izypzzp3ev-stack/ddc07f90-7035-11eb-a1ee-024c6ad462dd -r AWSEBAutoScalingGroup --region eu-west-1 --configsets Infra-EmbeddedPostBuild
2021/02/22 15:24:21.444174 [INFO] Finished executing the config set Infra-EmbeddedPostBuild.
2021/02/22 15:24:21.444193 [INFO] Executing instruction: CleanEbExtensions
2021/02/22 15:24:21.444214 [INFO] Cleaned ebextensions subdirectories from app staging directory.
2021/02/22 15:24:21.444219 [INFO] Executing instruction: RunAppDeployPreDeployHooks
2021/02/22 15:24:21.444241 [INFO] The dir .platform/hooks/predeploy/ does not exist in the application. Skipping this step...
2021/02/22 15:24:21.444246 [INFO] Executing instruction: stop X-Ray
2021/02/22 15:24:21.444256 [INFO] stop X-Ray ...
2021/02/22 15:24:21.444270 [INFO] Running command /bin/sh -c systemctl show -p PartOf xray.service
2021/02/22 15:24:21.450951 [WARN] stopProcess Warning: process xray is not registered
2021/02/22 15:24:21.450970 [INFO] Running command /bin/sh -c systemctl stop xray.service
2021/02/22 15:24:21.458328 [INFO] Executing instruction: Run Docker Container
2021/02/22 15:24:21.458345 [INFO] stop currently running containers...
2021/02/22 15:24:21.458360 [INFO] detected old app is not docker compose app
2021/02/22 15:24:21.458370 [INFO] Running command /bin/sh -c iptables-save \| grep -v added_by_elasticbeanstalk \| iptables-restore
2021/02/22 15:24:21.463202 [INFO] Running command /bin/sh -c systemctl show -p PartOf nginx.service
2021/02/22 15:24:21.468128 [WARN] deregisterProcess Warning: process nginx is not registered, skipping...
2021/02/22 15:24:21.468146 [INFO] Running command /bin/sh -c systemctl show -p PartOf eb-docker.service
2021/02/22 15:24:21.472976 [WARN] deregisterProcess Warning: process eb-docker is not registered, skipping...
2021/02/22 15:24:21.473005 [INFO] Running command /bin/sh -c systemctl show -p PartOf eb-docker-log.service
2021/02/22 15:24:21.478001 [WARN] deregisterProcess Warning: process eb-docker-log is not registered, skipping...
2021/02/22 15:24:21.478030 [INFO] stopping current container: 1fdd921108d0
2021/02/22 15:24:21.478040 [INFO] Running command /bin/sh -c docker ps \| grep -q 1fdd921108d0
2021/02/22 15:24:21.527668 [INFO] Running command /bin/sh -c docker ps \| grep -q 1fdd921108d0
2021/02/22 15:24:21.573694 [INFO] Running command /bin/sh -c docker container prune -f
2021/02/22 15:24:21.619174 [INFO] Total reclaimed space: 0B
2021/02/22 15:24:21.619248 [INFO] Running command /bin/sh -c docker rmi aws_beanstalk/current-app
2021/02/22 15:24:21.665243 [INFO] detected new app is not docker compose app
2021/02/22 15:24:21.665306 [INFO] Running command /bin/sh -c docker run -d --env-file /opt/elasticbeanstalk/deployment/env.list   e82b46a03aa1
2021/02/22 15:24:22.327060 [INFO] cd610502323b8744b09bb8a08b8d2fde65b3ffb7d1939b810aa3d249afeb9d4d
2021/02/22 15:24:27.327361 [INFO] Running command /bin/sh -c docker ps \| grep -q cd610502323b
2021/02/22 15:24:27.380095 [ERROR] docker container quit unexpectedly on 2021-02-22 15:24:27.380069995 +0000 UTC: Command /bin/sh -c docker ps \| grep -q cd610502323b failed with error exit status 1
2021/02/22 15:24:27.380133 [INFO] Running command /bin/sh -c docker logs cd610502323b
2021/02/22 15:24:27.427626 [INFO] Executing instruction: Clean up Docker
2021/02/22 15:24:27.427651 [INFO] Running command /bin/sh -c docker ps -aq
2021/02/22 15:24:27.472806 [INFO] cd610502323b
```

From `/aws/elasticbeanstalk/qa-mong-api/var/log/docker-events.log`

```
2021-02-22T15:24:18.444903154Z image pull hnskde/mong-api:master (name=hnskde/mong-api, org.opencontainers.image.created=2021-02-22T15:20:57.752Z, org.opencontainers.image.description=js scripts for qmongr, org.opencontainers.image.licenses=GPL-3.0, org.opencontainers.image.revision=94cf30f3c280dd1acc747f6267d4ae2e707ef98b, org.opencontainers.image.source=https://github.com/mong/qmongjs, org.opencontainers.image.title=qmongjs, org.opencontainers.image.url=https://github.com/mong/qmongjs, org.opencontainers.image.version=master)
2021-02-22T15:24:18.713041881Z container create eef3fa6ea839605bdb6fa7c45cb361e3030cc26a60cee85ec7b3174287cda8ac (image=sha256:2676c006a2d8e094c365f1208465458fda598f2403bc1801c5c10eca4e2f9b3e, name=youthful_borg, org.opencontainers.image.created=2021-02-22T15:20:57.752Z, org.opencontainers.image.description=js scripts for qmongr, org.opencontainers.image.licenses=GPL-3.0, org.opencontainers.image.revision=94cf30f3c280dd1acc747f6267d4ae2e707ef98b, org.opencontainers.image.source=https://github.com/mong/qmongjs, org.opencontainers.image.title=qmongjs, org.opencontainers.image.url=https://github.com/mong/qmongjs, org.opencontainers.image.version=master)
2021-02-22T15:24:18.794121487Z container destroy eef3fa6ea839605bdb6fa7c45cb361e3030cc26a60cee85ec7b3174287cda8ac (image=sha256:2676c006a2d8e094c365f1208465458fda598f2403bc1801c5c10eca4e2f9b3e, name=youthful_borg, org.opencontainers.image.created=2021-02-22T15:20:57.752Z, org.opencontainers.image.description=js scripts for qmongr, org.opencontainers.image.licenses=GPL-3.0, org.opencontainers.image.revision=94cf30f3c280dd1acc747f6267d4ae2e707ef98b, org.opencontainers.image.source=https://github.com/mong/qmongjs, org.opencontainers.image.title=qmongjs, org.opencontainers.image.url=https://github.com/mong/qmongjs, org.opencontainers.image.version=master)
2021-02-22T15:24:18.798759095Z image tag sha256:e82b46a03aa13b1bbbe9c508dc373cbb3d408f75303fb5b0482a2af646fe930d (name=aws_beanstalk/staging-app:latest, org.opencontainers.image.created=2021-02-22T15:20:57.752Z, org.opencontainers.image.description=js scripts for qmongr, org.opencontainers.image.licenses=GPL-3.0, org.opencontainers.image.revision=94cf30f3c280dd1acc747f6267d4ae2e707ef98b, org.opencontainers.image.source=https://github.com/mong/qmongjs, org.opencontainers.image.title=qmongjs, org.opencontainers.image.url=https://github.com/mong/qmongjs, org.opencontainers.image.version=master)
2021-02-22T15:24:21.731672191Z container create cd610502323b8744b09bb8a08b8d2fde65b3ffb7d1939b810aa3d249afeb9d4d (image=e82b46a03aa1, name=sad_merkle, org.opencontainers.image.created=2021-02-22T15:20:57.752Z, org.opencontainers.image.description=js scripts for qmongr, org.opencontainers.image.licenses=GPL-3.0, org.opencontainers.image.revision=94cf30f3c280dd1acc747f6267d4ae2e707ef98b, org.opencontainers.image.source=https://github.com/mong/qmongjs, org.opencontainers.image.title=qmongjs, org.opencontainers.image.url=https://github.com/mong/qmongjs, org.opencontainers.image.version=master)
2021-02-22T15:24:21.783702953Z network connect a86ab57a1dd06991ec5460094c4022b52948bb8943f4ee2e3661bf137d3de7bf (container=cd610502323b8744b09bb8a08b8d2fde65b3ffb7d1939b810aa3d249afeb9d4d, name=bridge, type=bridge)
2021-02-22T15:24:22.324135165Z container start cd610502323b8744b09bb8a08b8d2fde65b3ffb7d1939b810aa3d249afeb9d4d (image=e82b46a03aa1, name=sad_merkle, org.opencontainers.image.created=2021-02-22T15:20:57.752Z, org.opencontainers.image.description=js scripts for qmongr, org.opencontainers.image.licenses=GPL-3.0, org.opencontainers.image.revision=94cf30f3c280dd1acc747f6267d4ae2e707ef98b, org.opencontainers.image.source=https://github.com/mong/qmongjs, org.opencontainers.image.title=qmongjs, org.opencontainers.image.url=https://github.com/mong/qmongjs, org.opencontainers.image.version=master)
2021-02-22T15:24:22.569058806Z container die cd610502323b8744b09bb8a08b8d2fde65b3ffb7d1939b810aa3d249afeb9d4d (exitCode=1, image=e82b46a03aa1, name=sad_merkle, org.opencontainers.image.created=2021-02-22T15:20:57.752Z, org.opencontainers.image.description=js scripts for qmongr, org.opencontainers.image.licenses=GPL-3.0, org.opencontainers.image.revision=94cf30f3c280dd1acc747f6267d4ae2e707ef98b, org.opencontainers.image.source=https://github.com/mong/qmongjs, org.opencontainers.image.title=qmongjs, org.opencontainers.image.url=https://github.com/mong/qmongjs, org.opencontainers.image.version=master)
2021-02-22T15:24:22.640452537Z network disconnect a86ab57a1dd06991ec5460094c4022b52948bb8943f4ee2e3661bf137d3de7bf (container=cd610502323b8744b09bb8a08b8d2fde65b3ffb7d1939b810aa3d249afeb9d4d, name=bridge, type=bridge)
2021-02-22T15:24:27.620487444Z container destroy cd610502323b8744b09bb8a08b8d2fde65b3ffb7d1939b810aa3d249afeb9d4d (image=e82b46a03aa1, name=sad_merkle, org.opencontainers.image.created=2021-02-22T15:20:57.752Z, org.opencontainers.image.description=js scripts for qmongr, org.opencontainers.image.licenses=GPL-3.0, org.opencontainers.image.revision=94cf30f3c280dd1acc747f6267d4ae2e707ef98b, org.opencontainers.image.source=https://github.com/mong/qmongjs, org.opencontainers.image.title=qmongjs, org.opencontainers.image.url=https://github.com/mong/qmongjs, org.opencontainers.image.version=master)
2021-02-22T15:24:27.716576537Z image untag sha256:e82b46a03aa13b1bbbe9c508dc373cbb3d408f75303fb5b0482a2af646fe930d (name=sha256:e82b46a03aa13b1bbbe9c508dc373cbb3d408f75303fb5b0482a2af646fe930d, org.opencontainers.image.created=2021-02-22T15:20:57.752Z, org.opencontainers.image.description=js scripts for qmongr, org.opencontainers.image.licenses=GPL-3.0, org.opencontainers.image.revision=94cf30f3c280dd1acc747f6267d4ae2e707ef98b, org.opencontainers.image.source=https://github.com/mong/qmongjs, org.opencontainers.image.title=qmongjs, org.opencontainers.image.url=https://github.com/mong/qmongjs, org.opencontainers.image.version=master)
2021-02-22T15:24:27.717302077Z image delete sha256:e82b46a03aa13b1bbbe9c508dc373cbb3d408f75303fb5b0482a2af646fe930d (name=sha256:e82b46a03aa13b1bbbe9c508dc373cbb3d408f75303fb5b0482a2af646fe930d)
2021-02-22T15:24:27.720508239Z image untag sha256:2676c006a2d8e094c365f1208465458fda598f2403bc1801c5c10eca4e2f9b3e (name=sha256:2676c006a2d8e094c365f1208465458fda598f2403bc1801c5c10eca4e2f9b3e, org.opencontainers.image.created=2021-02-22T15:20:57.752Z, org.opencontainers.image.description=js scripts for qmongr, org.opencontainers.image.licenses=GPL-3.0, org.opencontainers.image.revision=94cf30f3c280dd1acc747f6267d4ae2e707ef98b, org.opencontainers.image.source=https://github.com/mong/qmongjs, org.opencontainers.image.title=qmongjs, org.opencontainers.image.url=https://github.com/mong/qmongjs, org.opencontainers.image.version=master)
2021-02-22T15:24:27.722238879Z image untag sha256:2676c006a2d8e094c365f1208465458fda598f2403bc1801c5c10eca4e2f9b3e (name=sha256:2676c006a2d8e094c365f1208465458fda598f2403bc1801c5c10eca4e2f9b3e, org.opencontainers.image.created=2021-02-22T15:20:57.752Z, org.opencontainers.image.description=js scripts for qmongr, org.opencontainers.image.licenses=GPL-3.0, org.opencontainers.image.revision=94cf30f3c280dd1acc747f6267d4ae2e707ef98b, org.opencontainers.image.source=https://github.com/mong/qmongjs, org.opencontainers.image.title=qmongjs, org.opencontainers.image.url=https://github.com/mong/qmongjs, org.opencontainers.image.version=master)
2021-02-22T15:24:29.858967823Z image delete sha256:2676c006a2d8e094c365f1208465458fda598f2403bc1801c5c10eca4e2f9b3e (name=sha256:2676c006a2d8e094c365f1208465458fda598f2403bc1801c5c10eca4e2f9b3e)
```

**Comment by arnfinn** [comment]
Trying locally:

```
$ docker pull hnskde/mong-api:master
master: Pulling from hnskde/mong-api
0a6724ff3fcd: Pull complete 
3b3c21ce1f8c: Pull complete 
560ed84bbbcc: Pull complete 
281a19a6c438: Pull complete 
3333f825adb1: Pull complete 
f3d74025eb22: Pull complete 
c81985598297: Pull complete 
313369890854: Pull complete 
Digest: sha256:b02fdcfcd93af211dec9456935ccd171d55b69bc71e30aa0dce4affe9c039f1f
Status: Downloaded newer image for hnskde/mong-api:master
docker.io/hnskde/mong-api:master

$ docker run hnskde/mong-api:master
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/app/build'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by arnfinn** [comment]
The Docker image produced by github actions was building the app in the root folder (front end) and not the app in `api/` folder. Problem solved by moving api to separate repository.
